// Mocks generated by Mockito 5.0.2 from annotations
// in flutter_currency_converter/test/repository_test/currency_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_currency_converter/src/provider/currency_provider.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tuple/tuple.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeTuple2<T1, T2> extends _i1.Fake implements _i2.Tuple2<T1, T2> {}

/// A class which mocks [CurrencyProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyProvider extends _i1.Mock implements _i3.CurrencyProvider {
  MockCurrencyProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Tuple2<Map<String, num>, int>> latest() =>
      (super.noSuchMethod(Invocation.method(#latest, []),
              returnValue: Future.value(_FakeTuple2<Map<String, num>, int>()))
          as _i4.Future<_i2.Tuple2<Map<String, num>, int>>);
  @override
  _i4.Future<Map<String, String>> symbols() =>
      (super.noSuchMethod(Invocation.method(#symbols, []),
              returnValue: Future.value(<String, String>{}))
          as _i4.Future<Map<String, String>>);
}
